version: '3.9'

services:
  my-api:
    container_name: my-api
    image: my-api
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
      - swagger-ui

  db:
    container_name: db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  swagger-ui:
      image: swaggerapi/swagger-ui
      ports:
        - "8002:8080"
      volumes:
        - ./swagger:/usr/share/nginx/html/swagger
      environment:
        API_URL: swagger/api.yaml


volumes:
  pgdata: {}